routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/* Route::get('/', function () {
    return view('index');
}); */

//Route::resource('user', 'UserController');
Route::resource('art', 'ArtController');
Route::resource('image', 'ImageController');
Route::resource('event', 'EventController');
Route::resource('video', 'VideoController');
Route::get('/sendemail', 'SendEmailController@ship')->name('sendemail');
Route::get('/stripe', 'StripePaymentController@stripe');
Route::post('/stripe', 'StripePaymentController@stripePost')->name('stripe.post');

Auth::routes(['verify'=>true]);

Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/about', 'HomeController@about')->name('about');
Route::get('/contact', 'HomeController@contact')->name('contact');

// Route::get('/paypal', 'PayPalController@show')->name('paypal.payment.show');

//Route::resource('/paypal', 'PayPalController');
Route::middleware(['auth','verified', 'role:admin'])->group(function () {
    // contains all dashboard routes

    Route::prefix('admin')->group(function () {
        Route::get('dashboard', 'Dashboard\AdminController@dashboard')->name('dashboard');
        Route::post('dashboard/image-upload', 'ImageController@store')->name('image.upload.post');
        Route::get('dashboard/image-upload', 'ImageController@create')->name('image.upload');
        Route::post('dashboard/arts', 'ArtController@store')->name('art.save');
        Route::post('dashboard/arts-update', 'ArtController@update')->name('art.update');
        Route::get('dashboard/arts', 'ArtController@create')->name('art.see');
        Route::post('dashboard/event', 'EventController@store')->name('event.save');
        Route::get('dashboard/event', 'EventController@create')->name('event.see');
        Route::post('dashboard/eventSearch', 'EventController@search')->name('event.search');
        Route::get('dashboard/event-and-art-control', 'EventArtController@create')->name('eventOrArt.show');
        Route::get('dashboard/event-and-art-control-edit', 'EventArtController@edit')->name('eventOrArt.update');
        Route::get('dashboard/event-art-delate', 'EventArtController@destroy')->name('eventOrArt.delate');
        Route::get('dashboard/mediaUploadPage', 'MediaController@create')->name('media.show');
        Route::post('dashboard/mediaUploadPost', 'MediaController@store')->name('media.upload');
        Route::get('dashboard/mediaUpload', 'MediaController@auto_complet')->name('media.autocomplet');


        Route::get('/art/list', "Dashboard\ArtController@index")->name('admin.art.list');
        Route::get('/art/create', "Dashboard\ArtController@create")->name('admin.art.create');
        Route::get('/art/edit/{art}/', "Dashboard\ArtController@edit")->name('admin.art.edit');
        Route::get('/art/show/{art}/', "Dashboard\ArtController@show")->name('admin.art.show');
        Route::put('/art/store', "Dashboard\ArtController@store")->name('admin.art.store');
        Route::post('/art/update/{art}', "Dashboard\ArtController@udpate")->name('admin.art.update');
        Route::delete('/art/delete/{art}', "Dashboard\ArtController@delete")->name('admin.art.delete');

        Route::get('/event/list', "Dashboard\EventController@index")->name('admin.event.list');
        Route::get('/event/create', "Dashboard\EventController@create")->name('admin.event.create');
        Route::get('/event/edit/{event}/', "Dashboard\EventController@edit")->name('admin.event.edit');
        Route::get('/event/show/{event}/', "Dashboard\EventController@show")->name('admin.event.show');
        Route::put('/event/store', "Dashboard\EventController@store")->name('admin.event.store');
        Route::post('/event/update/{event}', "Dashboard\EventController@udpate")->name('admin.event.update');
        Route::delete('/event/delete/{event}', "Dashboard\EventController@delete")->name('admin.event.delete');

    });

    // Route::get('/shop/detail','ShopController@detail')->name('shop.detail');
    // Route::get('/shop/checkout','ShopController@checkout')->name('shop.checkout');
    // Route::get('/shop/add-cart-item','ShopController@addCartItem')->name('shop.add-cart-item');
    // Route::post('/shop/update-cart-item','ShopController@updateCartItem')->name('shop.update-cart-item');
    // Route::delete('/shop/remove-cart-item/{idCartItem}','ShopController@removeCartItem')->name('shop.remove-cart-item');
    // Route::post('/shop/checkout/complet','ShopController@completCheckout')->name('shop.checkout.complet');
    //completCheckout ('shop.checkout.complet')
});
Route::middleware(['auth','verified'])->group(function () {

    Route::post('/paypal/payment/create', 'PayPalController@createOrder')->name('paypal.payment.create');
    Route::get('/paypal/payment/cancel', 'PayPalController@cancel')->name('paypal.payment.cancel');
    Route::post('/paypal/payment/success', 'PayPalController@getOrder')->name('paypal.payment.success');
    Route::get('/shop/detail','ShopController@detail')->name('shop.detail');
    Route::get('/shop/checkout','ShopController@checkout')->name('shop.checkout');
    Route::post('/shop/add-cart-item','ShopController@addCartItem')->name('shop.add-cart-item');
    Route::post('/shop/update-cart-item','ShopController@updateCartItem')->name('shop.update-cart-item');
    Route::delete('/shop/remove-cart-item/{idCartItem}','ShopController@removeCartItem')->name('shop.remove-cart-item');
    Route::post('/shop/checkout/complet','ShopController@completCheckout')->name('shop.checkout.complet');
    //completCheckout ('shop.checkout.complet')
});

app/Models/Image.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Image extends Model
{
    use SoftDeletes;

    use SoftDeletes;
    protected $table = 'image';
    public $timestamps = true;
    protected $fillable = array('url', 'alt');

    public function imageable()
    {
        return $this->morphTo();
    }

    /*
     * This function is to retrive a full path of images
     * User avatar image src
     */
    public function getImageSrcAttribute() {


        if($this->imageable_type == 'App\Models\Art' ){
            // just to prevent unexisting file
            if(!file_exists(public_path('storage/images/arts/' . $this->url)))
            {
                $this->update(['url' => 'default_art.jpg']);
            }

            return asset("storage/images/arts/" . $this->url);
        }

        else if($this->imageable_type == 'App\Models\Event') {
            // just to prevent unexisting file
            if(!file_exists(public_path('storage/images/events/' . $this->url)))
            {
                $this->update(['url' => 'default_event.jpg']);
            }

            return asset("storage/images/events/" . $this->url);
        }

        else if($this->imageable_type == 'App\User') {
            // just to prevent unexisting file
            if(!file_exists(public_path('storage/images/users/' . $this->url)))
            {
                $this->update(['url' => 'default.png']);
            }

            return asset("storage/images/users/" . $this->url);
        }
        else {
            // just to prevent unexisting file
            if(!file_exists(public_path('storage/images/' . $this->url)))
            {
                $this->update(['url' => 'default_others.jpg']);
            }

            return asset("storage/images/others/" . $this->url);
        }
    }
}

resources/views/about.blade.php
@extends('layouts.app')

@section('content')
@breadcrumb([
    'breadcrumb_title' => "About",
    'breadcrumb_title_span' => "us"
]);
@endbreadcrumb
<section id="primary" class="content-full-width"> <!-- **Primary Starts Here** -->
    <div class="container">
        <div class="main-title animate" data-animation="pullDown" data-delay="100">
            <h3> About me </h3>
            <p> {{ trans("owner.about-me-sub-title") }}  </p>
        </div>
        <div class="dt-sc-service-content">
            <p> {{ trans("owner.about-little-intro") }} </p>
        </div>
        <div class="dt-sc-hr-invisible"></div>
        <div class="service-grid">
            <div class="dt-sc-one-half column first animate" data-animation="fadeInDown" data-delay="100">
                <img src="{{ asset('assets/images/about-img.png') }}" alt="" title="">
            </div>
            <div class="dt-sc-one-half column">
                <div class="dt-sc-icon-content-wrapper"><!-- *dt-sc-icon-content-wrapper Starts here** -->
                    <div class="dt-sc-one-half column first">
                        <div class="dt-sc-ico-content animate" data-animation="fadeInRight" data-delay="100">
                            <h6>About Me</h6>
                            <p><span>Name:</span> {{ trans("owner.name") }} </p>
                            <p><span>Location:</span>{{ trans("owner.location") }}</p>
                            <div class="dt-sc-hr-invisible-very-small"></div>
                            <p>{{ trans("owner.about-little-intro") }}</p>
                        </div>
                    </div>
                    <div class="dt-sc-one-half column dt-sc-icon-wrapper">
                        <div class="dt-sc-icon"><i class="fa fa-user-secret animate" data-animation="fadeInLeft" data-delay="100"></i></div>
                    </div>
                </div><!-- *dt-sc-icon-content-wrapper Ends here** -->
            </div>
            <div class="dt-sc-one-half column">
                <div class="dt-sc-icon-content-wrapper left"><!-- *dt-sc-icon-content-wrapper Starts here** -->
                    <div class="dt-sc-one-half column first dt-sc-icon-wrapper">
                        <div class="dt-sc-icon"><i class="fa fa-whatsapp animate" data-animation="fadeInLeft" data-delay="100"></i></div>
                    </div>
                    <div class="dt-sc-one-half column first">
                        <div class="dt-sc-ico-content animate" data-animation="fadeInRight" data-delay="100">
                            <h6>Get in touch</h6>
                            <p><i class="fa fa-map-marker"></i>{{ trans("owner.address") }}</p>
                            <p><i class="fa fa-phone"></i> {{ trans("owner.phone") }} </p>
                            <p><i class="fa fa-envelope"></i><a href="#">{{ trans("owner.email") }}</a></p>
                            <div class="dt-sc-hr-invisible-very-small"></div>
                            <h6>Follow me on</h6>
                            <ul class="type3 dt-sc-social-icons">
                                <li class="twitter"><a href="#"> <i class="fa fa-twitter"></i> </a></li>
                                <li class="facebook"><a href="#"> <i class="fa fa-facebook"></i> </a></li>
                                <li class="google"><a href="#"> <i class="fa fa-google"></i> </a></li>
                                <li class="dribbble"><a href="#"> <i class="fa fa-dribbble"></i> </a></li>
                            </ul>
                        </div>
                    </div>
                </div><!-- *dt-sc-icon-content-wrapper Ends here** -->
            </div>
        </div>
    </div>
</section><!-- **Primary Ends Here** -->

@endsection

resources/views/art-detail.blade.php
@extends('layouts.app')

@section('content')
@if($art->type == "art")
    @breadcrumb([
        'breadcrumb_title' => "Art",
        'breadcrumb_title_span' => "Detail"
    ]);
    @endbreadcrumb
@else
    @breadcrumb([
    'breadcrumb_title' => "Tattoo",
    'breadcrumb_title_span' => "Detail"
    ]);
    @endbreadcrumb
@endif
<div class="container">
    <div class="main-title animate" data-animation="pullDown" data-delay="100">
    <h3>{{ $art->name }}</h3>
    </div>
    <section id="secondary" class="secondary-sidebar secondary-has-left-sidebar"><!-- **Secondary Starts Here** -->
        <aside class="widget widget_search">
            <div class="widgettitle sub-title">
                <h3>It is nice right ?</h3>
            </div>
        <a class="dt-sc-button large type3 with-icon" id="addCartItemButton" data-url="{{ route('shop.add-cart-item') }}" href="#"><i class="fa fa-shopping-cart"></i><span>Add to the cart</span></a>
            <div id="ajax_subscribe_msg"></div>
        </aside>
        {{-- <aside class="widget widget_categories">
            <div class="widgettitle sub-title">
                <h3> Categories </h3>
            </div>
            <ul>
                <li class="cat-item"><a title="#" href="#">Corporate<span> 2</span></a></li>
                <li class="cat-item"><a title="#" href="#">Design<span> 3</span></a></li>
                <li class="cat-item"><a title="#" href="#">Learning<span> 2</span></a></li>
                <li class="cat-item"><a title="#" href="#">Tools<span> 1</span></a></li>
                <li class="cat-item"><a title="#" href="#">Training<span> 3</span></a></li>
            </ul>
        </aside> --}}
        <div class="project-details">
            <ul class="client-details" style="padding-left: 0px;">
                <li><p><span>Price :</span>$ {{ $art->price }}</p></li>
                <li><p><span>Quantity :</span>{{ $art->quantity }}</p></li>
                <li><p><span>Time :</span>{{ dateDiff($art->start_at, $art->end_at) }}</p></li>
                <li><p><span>technique :</span>{{ showTabDetail($art->techniques) }}</p></li>
                <li><p><span>Equipment :</span>{{ showTabDetail($art->equipments) }}</p></li>
                <li><p><span>Support :</span>{{ showTabDetail($art->supports) }}</p></li>
            </ul>
        </div>

        {{-- <aside class="widget widget_popular_entries">
            <div class="widgettitle sub-title">
                <h3> Latest Gallery</h3>
            </div>
            <div class="recent-gallery-widget">
                <ul>
                    <li>
                        <a class="entry-thumb" href="#"><img alt="Enjoy Life with Family" src="http://placehold.it/955x470&text=Portfolio+Image"></a>
                        <h5><a href="#"> Cowboy of Timberland </a></h5>
                        <p>Vivamus ullamcorper, enim at varius molestie, nunc libero pulvinar sapien, quis fringilla purus mi vitae tellus.</p>
                    </li>
                </ul>
            </div>
        </aside> --}}
        {{-- <aside class="widget widget_tag_cloud">
            <div class="widgettitle sub-title">
                <h3> Tags </h3>
            </div>
            <div class="tagcloud type3">
                <a title="1 topic" href="#">Sketch</a>
                <a title="1 topic" href="#">Oil color</a>
                <a title="1 topic" href="#">Acrylic</a>
                <a title="1 topic" href="#">Sculpture</a>
                <a title="1 topic" href="#">Crayons</a>
                <a title="1 topic" href="#">Art</a>
            </div>
        </aside>                                                                           	 --}}
    </section><!-- **Secondary Ends Here** -->
    <section id="primary" class="with-sidebar with-left-sidebar">
        <article>
            <div class="dt-sc-one-column column first">
                <div class="recent-gallery-container">
                    <ul class="recent-gallery">
                        @foreach ($art->images as $art_image)
                        <li> <img src="{{ $art_image->image_src }}" alt="{{ $art_image->alt }}"/> </li>
                        @endforeach
                    </ul>
                    {{-- <div id="bx-pager">
                        <a href="#" data-slide-index='0'><img src='http://placehold.it/1920x800&text=Service+Thumb+1/000000' alt='image' /></a>
                        <a href="#" data-slide-index='1'><img src='http://placehold.it/1920x800&text=Service+Thumb+2/000000' alt='image' /></a>
                        <a href="#" data-slide-index='2'><img src='http://placehold.it/1920x800&text=Service+Thumb+3/000000' alt='image' /></a>
                        <a href="#" data-slide-index='3'><img src='http://placehold.it/1920x800&text=Service+Thumb+4/000000' alt='image' /></a>
                    </div>                            	 --}}
                </div>
            </div>
            <div class="dt-sc-hr-invisible-small"> </div>
            <div class="dt-sc-two-third column first animate" data-animation="fadeInLeft" data-delay="100">
                <h3>{{ $art->name }}</h3>
                <p>{{ $art->description }}</p>
            </div>
            {{-- <div class="dt-sc-one-third column animate" data-animation="fadeInRight" data-delay="100">
                <div class="dt-sc-project-details">
                    <h5>Other Details</h5>
                    <div class="enquiry-details">
                        <p> <i class="fa fa-cab"></i> 121 King St, Melbourne VIC 3, Australia </p>
                        <p><i class="fa fa-mortar-board"></i> Stephen Jones</p>
                        <p><i class="fa fa-wrench"></i> Crayons, Sketch, Scissors</p>
                        <p> <i class="fa fa-tags"></i> Arcrylic, Sculpture, Canvas</p>
                        <p> <i class="fa fa-globe"></i> <a href="#"> envato.com </a> </p>
                    </div>
                    <h5>Social Sharing</h5>
                    <ul class="type3 dt-sc-social-icons">
                        <li class="twitter"><a href="#"> <i class="fa fa-twitter"></i> </a></li>
                        <li class="facebook"><a href="#"> <i class="fa fa-facebook"></i> </a></li>
                        <li class="google"><a href="#"> <i class="fa fa-google"></i> </a></li>
                        <li class="dribbble"><a href="#"> <i class="fa fa-dribbble"></i> </a></li>
                    </ul>
                </div>
            </div>
            <div class="dt-sc-post-pagination">
                <a class="dt-sc-button small type3 with-icon prev-post" href="#"> <span> Previous Post </span> <i class="fa fa-hand-o-left"> </i> </a>
                <a class="dt-sc-button small type3 with-icon next-post" href="#"><i class="fa fa-hand-o-right"> </i>  <span> Next Post </span> </a>
            </div>                         --}}
        </article>
    </section>
    <div class="dt-sc-hr-invisible-small"></div>
</div><!-- **Container Ends Here** -->
@if($art->type == "art")
    <div class="container">
        <div class="main-title animate" data-animation="pullDown" data-delay="100">
            <h3> Related Art </h3>
        </div>
    </div>
    @related_art(['related_arts' => $related_arts, 'type' => 'art'])
    @endrelated_art
@else
    <div class="container">
        <div class="main-title animate" data-animation="pullDown" data-delay="100">
            <h3> Related Tattoo </h3>
        </div>
    </div>
    @related_art(['related_arts' => $related_arts, 'type' => 'tattoo'])
    @endrelated_art
@endif

@endsection

@push('script')
<script>
    jQuery(document).ready(function(jQuery){
        jQuery("#addCartItemButton").on("click", function(event){
            jQuery(".loader-wrapper").fadeIn(500);

            event.preventDefault();

            jQuery.ajax({
                //type of submit
                type: 'POST',
                url: jQuery(this).data('url'),
                // data to be sent
                data: {
                    idArt: {{ $art->id }},
                    price: {{ $art->price }},
                    quantity: {{ $art->quantity }}
                },
                // Function to be exceuted in case of successfulled operation
                success: function success(data) {
                    console.log("Here is the response" + data); // and when you done:
                    jQuery(".loader-wrapper").fadeOut(500);
                    if(data.status === true) {
                        jQuery("#cart-count-items").html("Shopping Bag: "+data["items_number"]+" items");
                        jQuery("#cart-count-subtotal").html("($ "+data["subtotal"]+" )");
                        success_flash('The art was successfully added into your cart');
                    } else {
                        error_flash('The art was not added into your cart because an error occur');
                    }
                },
                // Function to be exceuted in case of failed operation
                error: function error(error) {
                    jQuery(".loader-wrapper").fadeOut(500);
                    notification('An error occur please try later', 'error', 8000);
                    console.log(error.status);
                }
            });
        });
    });
</script>
@endpush

resources/views/contact.blade.php
@extends('layouts.app')

@section('content')
@breadcrumb([
    'breadcrumb_title' => "Contact",
    'breadcrumb_title_span' => "us"
]);
@endbreadcrumb
<section id="primary" class="content-full-width"><!-- **Primary Starts Here** -->
    <div class="fullwidth-section"><!-- Full-width section Starts Here -->
        <div class="container">
            <div class="main-title animate" data-animation="pullDown" data-delay="100">
                <h3> Contact </h3>
                <p> {{ trans("owner.contact-sub-title") }} </p>
            </div>
        </div>
        <div class="contact-section"><!-- **contact-section Starts Here** -->
            <div id="contact_map" class="animate" data-animation="fadeInRight" data-delay="100"></div>
            <div class="dt-sc-contact-info animate" data-animation="fadeInLeft" data-delay="100">
                <h3>Artist Info</h3>
                <div class="dt-sc-contact-details"><span class="fa fa-map-marker"></span> Address: {{ trans("owner.adress") }} </div>
                <div class="dt-sc-contact-details"><span class="fa fa-tablet"></span> Phone: {{ trans("owner.phone") }} </div>
                <div class="dt-sc-contact-details"><span class="fa fa-envelope"></span> Email: <a href="mailto:{{ trans("owner.email") }}">{{ trans("owner.email") }}</a> </div>
                <ul class="type3 dt-sc-social-icons">
                    <li class="twitter"><a href="#"> <i class="fa fa-twitter"></i> </a></li>
                    <li class="facebook"><a href="#"> <i class="fa fa-facebook"></i> </a></li>
                    <li class="google"><a href="#"> <i class="fa fa-google"></i> </a></li>
                    <li class="dribbble"><a href="#"> <i class="fa fa-dribbble"></i> </a></li>
                    <li class="pinterest"><a href="#"> <i class="fa fa-pinterest"></i> </a></li>
                    <li class="linkedin"><a href="#"> <i class="fa fa-linkedin"></i> </a></li>
                    <li class="flickr"><a href="#"> <i class="fa fa-flickr"></i> </a></li>
                    <li class="tumblr"><a href="#"> <i class="fa fa-tumblr"></i> </a></li>
                </ul>
            </div>
        </div><!-- **contact-section Ends Here** -->
        <div class="dt-sc-hr-invisible-toosmall"></div>
        <div class="container">
            <div class="dt-sc-three-fourth column first animate" data-animation="fadeInDown" data-delay="100">
                <h3>Get in Touch</h3>
                <form class="enquiry-form" action="php/send.php" method="post" novalidate="novalidate" name="enqform" >
                    <div class="column dt-sc-one-third first">
                        <p class="input-text">
                            <input class="input-field" type="text" required="" name="txtname" title="Enter your Name" placeholder="Name *"/>
                        </p>
                    </div>
                    <div class="column dt-sc-one-third">
                        <p class="input-text">
                            <input class="input-field" type="email" required="" autocomplete="off" name="txtemail" title="Enter your valid id" placeholder="Email *"/>
                        </p>
                    </div>
                    <div class="column dt-sc-one-third">
                        <p class="input-text">
                            <input class="input-field" type="text" autocomplete="off" placeholder="Website"/>
                        </p>
                    </div>
                    <p class="input-text">
                        <textarea class="input-field" required="" rows="3" cols="5" name="txtmessage" title="Enter your Message" placeholder="Message *"></textarea>
                    </p>

                    <p class="submit"> <input type="submit" value="Send" name="submit" class="button" /> </p>
                </form>
                <div id="ajax_contactform_msg"></div>
            </div>
            {{--<div class="dt-sc-one-fourth column animate" data-animation="fadeInRight" data-delay="100">
                <h5>London Office</h5>
                <div class="enquiry-details">
                    <p> <i class="fa fa-cab"></i> 121 King St, Melbourne VIC 3, Australia </p>
                    <p> <i class="fa fa-phone"></i> +61 3 8376 6284 </p>
                    <p> <i class="fa fa-globe"></i> <a href="#"> envato.com </a> </p>
                    <p> <i class="fa fa-envelope"></i> <a href="#"> redart@gmail.com </a> </p>
                </div>
                <h5>Business Hours</h5>
                <ul class="dt-sc-working-hours">
                    <li>Hotline is available for 24 hours a day!..</li>
                    <li>Monday - Friday :<span> 8am to 6pm</span></li>
                    <li>Saturday : <span>10am to 2pm</span></li>
                    <li>Sunday : <span>Closed</span></li>
                </ul>
            </div>--}}
            {{--<div class="newsletter"><!--Newsletter Form Starts Here -->
                    <h3>Newsletter</h3>
                    <form method="post" class="mailchimp-form dt-sc-one-half column first animate" data-animation="stretchLeft" data-delay="100" name="frmnewsletter" action="php/subscribe.php">
                        <p class="input-text">
                            <input class="input-field" type="email" name="mc_email" value="" required/>
                            <label class="input-label">
                                    <i class="fa fa-envelope-o icon"></i>
                                    <span class="input-label-content">Mail</span>
                                </label>
                            <input type="submit" name="submit" class="submit" value="Subscribe" />
                        </p>
                    </form>
                    <div id="ajax_subscribe_msg"></div>

                    <div class="newsletter-text animate dt-sc-one-half column" data-animation="stretchRight" data-delay="100"> <i class="fa fa-envelope-o"> </i> Feel free to place your Mail_ID and Subscribe to our Newsletter here. So that, you can receive our exiting Updates and Offers with no wait! </div>
            </div><!--Newsletter Form Ends Here -->--}}
        </div>
    </div><!-- Full-width section Ends Here -->
</section><!-- **Primary Ends Here** -->

@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection